"""Prominent hedge funds / managers whose US long book is public via 13F.
`search` = EDGAR filer-name prefixes to try; `style` decides how much a
long-only clone can mean.  CIKs are resolved by resolve_universe() and
verified against actual 13F-HR filing counts, then cached in funds.json."""

STYLES = {
    "ls":     ("Long/short equity", "Clone tracks the long book; shorts and hedges are invisible."),
    "conc":   ("Concentrated long / value", "Clone is close to the real book — few positions, low turnover."),
    "act":    ("Activist", "Clone is close; positions are large, public and long-held."),
    "event":  ("Event-driven / credit", "Clone misses the credit and arbitrage book — partial at best."),
    "multi":  ("Multi-strategy / quant", "Clone is NOT meaningful: thousands of hedged positions, derivatives, high turnover."),
    "macro":  ("Global macro", "Clone is NOT meaningful: the book is futures, FX and rates, not US stocks."),
    "fo":     ("Family office", "Clone tracks the disclosed US long book of a closed fund."),
    "lo":     ("Long-only asset manager", "Clone tracks the book well — long-only, diversified, low turnover."),
    "mm":     ("Market maker", "Clone is NOT meaningful: a 13F here is trading inventory, hedged and 45 days stale, not a portfolio."),
}

FUNDS = [
    # --- Tiger cubs and long/short equity
    dict(slug="tiger-global", name="Tiger Global Management", manager="Chase Coleman", style="ls", search=["TIGER GLOBAL MANAGEMENT"]),
    dict(slug="lone-pine", name="Lone Pine Capital", manager="Stephen Mandel", style="ls", search=["LONE PINE CAPITAL"]),
    dict(slug="viking", name="Viking Global Investors", manager="Andreas Halvorsen", style="ls", search=["VIKING GLOBAL INVESTORS"]),
    dict(slug="coatue", name="Coatue Management", manager="Philippe Laffont", style="ls", search=["COATUE MANAGEMENT"]),
    dict(slug="maverick", name="Maverick Capital", manager="Lee Ainslie", style="ls", search=["MAVERICK CAPITAL"]),
    dict(slug="d1", name="D1 Capital Partners", manager="Daniel Sundheim", style="ls", search=["D1 CAPITAL PARTNERS"]),
    dict(slug="altimeter", name="Altimeter Capital", manager="Brad Gerstner", style="ls", search=["ALTIMETER CAPITAL MANAGEMENT"]),
    dict(slug="whale-rock", name="Whale Rock Capital", manager="Alex Sacerdote", style="ls", search=["WHALE ROCK CAPITAL MANAGEMENT"]),
    dict(slug="dragoneer", name="Dragoneer Investment Group", manager="Marc Stad", style="ls", search=["DRAGONEER INVESTMENT GROUP"]),
    dict(slug="light-street", name="Light Street Capital", manager="Glen Kacher", style="ls", search=["LIGHT STREET CAPITAL MANAGEMENT"]),
    dict(slug="glenview", name="Glenview Capital", manager="Larry Robbins", style="ls", search=["GLENVIEW CAPITAL MANAGEMENT"]),
    dict(slug="third-point", name="Third Point", manager="Daniel Loeb", style="act", search=["THIRD POINT LLC"]),
    dict(slug="greenlight", name="Greenlight Capital", manager="David Einhorn", style="ls", search=["GREENLIGHT CAPITAL INC"]),
    dict(slug="pershing-square", name="Pershing Square", manager="Bill Ackman", style="act", search=["PERSHING SQUARE CAPITAL MANAGEMENT"]),
    dict(slug="appaloosa", name="Appaloosa", manager="David Tepper", style="event", search=["APPALOOSA MANAGEMENT LP", "APPALOOSA LP"]),
    dict(slug="atreides", name="Atreides Management", manager="Gavin Baker", style="ls", search=["ATREIDES MANAGEMENT"]),
    dict(slug="situational-awareness", name="Situational Awareness", manager="Leopold Aschenbrenner", style="ls", search=["SITUATIONAL AWARENESS LP"]),
    dict(slug="scion", name="Scion Asset Management", manager="Michael Burry", style="conc", search=["SCION ASSET MANAGEMENT"]),
    dict(slug="baupost", name="Baupost Group", manager="Seth Klarman", style="conc", search=["BAUPOST GROUP"]),
    dict(slug="elliott", name="Elliott Investment Management", manager="Paul Singer", style="act", search=["ELLIOTT INVESTMENT MANAGEMENT", "ELLIOTT MANAGEMENT CORP"]),
    dict(slug="starboard", name="Starboard Value", manager="Jeffrey Smith", style="act", search=["STARBOARD VALUE LP"]),
    dict(slug="jana", name="JANA Partners", manager="Barry Rosenstein", style="act", search=["JANA PARTNERS"]),
    dict(slug="trian", name="Trian Fund Management", manager="Nelson Peltz", style="act", search=["TRIAN FUND MANAGEMENT"]),
    dict(slug="valueact", name="ValueAct Capital", manager="Mason Morfit", style="act", search=["VALUEACT HOLDINGS", "VALUEACT CAPITAL MANAGEMENT"]),
    dict(slug="icahn", name="Icahn Enterprises / Icahn Capital", manager="Carl Icahn", style="act", search=["ICAHN CARL C", "ICAHN CAPITAL LP"]),
    dict(slug="paulson", name="Paulson & Co", manager="John Paulson", style="event", search=["PAULSON & CO"]),
    dict(slug="soros", name="Soros Fund Management", manager="Soros family office", style="fo", search=["SOROS FUND MANAGEMENT"]),
    dict(slug="duquesne", name="Duquesne Family Office", manager="Stanley Druckenmiller", style="fo", search=["DUQUESNE FAMILY OFFICE"]),
    dict(slug="renaissance", name="Renaissance Technologies", manager="Jim Simons (quant)", style="multi", search=["RENAISSANCE TECHNOLOGIES"]),
    dict(slug="bridgewater", name="Bridgewater Associates", manager="Ray Dalio (macro)", style="macro", search=["BRIDGEWATER ASSOCIATES"]),
    dict(slug="millennium", name="Millennium Management", manager="Israel Englander", style="multi", search=["MILLENNIUM MANAGEMENT LLC"]),
    dict(slug="citadel", name="Citadel Advisors", manager="Ken Griffin", style="multi", search=["CITADEL ADVISORS LLC"]),
    dict(slug="de-shaw", name="D. E. Shaw & Co", manager="David Shaw (quant)", style="multi", search=["D. E. SHAW & CO", "SHAW D E & CO"]),
    dict(slug="two-sigma", name="Two Sigma Investments", manager="Overdeck / Siegel (quant)", style="multi", search=["TWO SIGMA INVESTMENTS"]),
    dict(slug="aqr", name="AQR Capital Management", manager="Cliff Asness (quant)", style="multi", search=["AQR CAPITAL MANAGEMENT"]),
    dict(slug="point72", name="Point72 Asset Management", manager="Steve Cohen", style="multi", search=["POINT72 ASSET MANAGEMENT"]),
    dict(slug="balyasny", name="Balyasny Asset Management", manager="Dmitry Balyasny", style="multi", search=["BALYASNY ASSET MANAGEMENT"]),
    dict(slug="exoduspoint", name="ExodusPoint Capital", manager="Michael Gelband", style="multi", search=["EXODUSPOINT CAPITAL MANAGEMENT"]),
    dict(slug="farallon", name="Farallon Capital", manager="Andrew Spokes", style="event", search=["FARALLON CAPITAL MANAGEMENT"]),
    dict(slug="davidson-kempner", name="Davidson Kempner", manager="Anthony Yoseloff", style="event", search=["DAVIDSON KEMPNER CAPITAL MANAGEMENT"]),
    dict(slug="king-street", name="King Street Capital", manager="Brian Higgins", style="event", search=["KING STREET CAPITAL MANAGEMENT"]),
    dict(slug="sculptor", name="Sculptor (Och-Ziff)", manager="Jimmy Levin", style="multi", search=["SCULPTOR CAPITAL LP", "OCH-ZIFF CAPITAL MANAGEMENT"]),
    dict(slug="marshall-wace", name="Marshall Wace", manager="Paul Marshall / Ian Wace", style="ls", search=["MARSHALL WACE"]),
    dict(slug="adage", name="Adage Capital", manager="Phill Gross / Robert Atchinson", style="ls", search=["ADAGE CAPITAL PARTNERS"]),
    dict(slug="tci", name="TCI Fund Management", manager="Chris Hohn", style="conc", search=["TCI FUND MANAGEMENT"]),
    dict(slug="egerton", name="Egerton Capital", manager="John Armitage", style="ls", search=["EGERTON CAPITAL"]),
    dict(slug="lansdowne", name="Lansdowne Partners", manager="Peter Davies", style="ls", search=["LANSDOWNE PARTNERS"]),
    dict(slug="eminence", name="Eminence Capital", manager="Ricky Sandler", style="ls", search=["EMINENCE CAPITAL"]),
    dict(slug="sachem-head", name="Sachem Head Capital", manager="Scott Ferguson", style="act", search=["SACHEM HEAD CAPITAL MANAGEMENT"]),
    dict(slug="corvex", name="Corvex Management", manager="Keith Meister", style="act", search=["CORVEX MANAGEMENT"]),
    dict(slug="abrams", name="Abrams Capital", manager="David Abrams", style="conc", search=["ABRAMS CAPITAL MANAGEMENT"]),
    dict(slug="cantillon", name="Cantillon Capital", manager="William von Mueffling", style="conc", search=["CANTILLON CAPITAL MANAGEMENT"]),
    dict(slug="himalaya", name="Himalaya Capital", manager="Li Lu", style="conc", search=["HIMALAYA CAPITAL MANAGEMENT"]),
    dict(slug="akre", name="Akre Capital", manager="Chuck Akre", style="conc", search=["AKRE CAPITAL MANAGEMENT"]),
    dict(slug="gotham", name="Gotham Asset Management", manager="Joel Greenblatt", style="ls", search=["GOTHAM ASSET MANAGEMENT"]),
    dict(slug="ruane-cunniff", name="Ruane, Cunniff & Goldfarb (Sequoia)", manager="Sequoia Fund", style="conc", search=["RUANE CUNNIFF & GOLDFARB", "RUANE, CUNNIFF & GOLDFARB"]),
    dict(slug="southeastern", name="Southeastern Asset Management (Longleaf)", manager="Mason Hawkins", style="conc", search=["SOUTHEASTERN ASSET MANAGEMENT"]),
    dict(slug="harris", name="Harris Associates (Oakmark)", manager="Bill Nygren", style="conc", search=["HARRIS ASSOCIATES L P", "HARRIS ASSOCIATES LP"]),
    dict(slug="tweedy-browne", name="Tweedy, Browne", manager="Tweedy, Browne partners", style="conc", search=["TWEEDY BROWNE CO LLC", "TWEEDY, BROWNE CO"]),
    dict(slug="yacktman", name="Yacktman Asset Management", manager="Stephen Yacktman", style="conc", search=["YACKTMAN ASSET MANAGEMENT"]),
    dict(slug="pzena", name="Pzena Investment Management", manager="Rich Pzena", style="conc", search=["PZENA INVESTMENT MANAGEMENT"]),
    dict(slug="polen", name="Polen Capital", manager="Dan Davidowitz", style="conc", search=["POLEN CAPITAL MANAGEMENT"]),
    dict(slug="sands", name="Sands Capital", manager="Frank Sands", style="conc", search=["SANDS CAPITAL MANAGEMENT"]),
    dict(slug="fundsmith", name="Fundsmith", manager="Terry Smith", style="conc", search=["FUNDSMITH LLP"]),
    dict(slug="pabrai", name="Pabrai Investment Funds", manager="Mohnish Pabrai", style="conc", search=["DALAL STREET LLC", "PABRAI INVESTMENT FUNDS"]),
    dict(slug="srs", name="SRS Investment Management", manager="Karthik Sarma", style="ls", search=["SRS INVESTMENT MANAGEMENT"]),
    dict(slug="hound", name="Hound Partners", manager="Jonathan Auerbach", style="ls", search=["HOUND PARTNERS"]),
    dict(slug="melvin", name="Melvin Capital (closed 2022)", manager="Gabe Plotkin", style="ls", search=["MELVIN CAPITAL MANAGEMENT"]),
    dict(slug="steadfast", name="Steadfast Capital", manager="Robert Pitts", style="ls", search=["STEADFAST CAPITAL MANAGEMENT"]),
    dict(slug="senator", name="Senator Investment Group", manager="Doug Silverman", style="event", search=["SENATOR INVESTMENT GROUP"]),
    dict(slug="soroban", name="Soroban Capital", manager="Eric Mandelblatt", style="conc", search=["SOROBAN CAPITAL PARTNERS"]),
    dict(slug="suvretta", name="Suvretta Capital", manager="Aaron Cowen", style="ls", search=["SUVRETTA CAPITAL MANAGEMENT"]),
    dict(slug="matrix", name="Matrix Capital", manager="David Goel", style="ls", search=["MATRIX CAPITAL MANAGEMENT"]),
    dict(slug="darsana", name="Darsana Capital", manager="Anand Desai", style="conc", search=["DARSANA CAPITAL PARTNERS"]),
    dict(slug="impactive", name="Impactive Capital", manager="Lauren Taylor Wolfe", style="act", search=["IMPACTIVE CAPITAL"]),
    dict(slug="engaged", name="Engaged Capital", manager="Glenn Welling", style="act", search=["ENGAGED CAPITAL"]),
    dict(slug="tiger-management", name="Tiger Management (Robertson)", manager="Julian Robertson (family office)", style="fo", search=["TIGER MANAGEMENT LLC", "TIGER MANAGEMENT L L C"]),
    dict(slug="blue-ridge", name="Blue Ridge Capital (closed 2017)", manager="John Griffin", style="ls", search=["BLUE RIDGE CAPITAL"]),
    dict(slug="berkshire-13f", name="Berkshire Hathaway (13F holdings)", manager="Warren Buffett", style="conc", search=["BERKSHIRE HATHAWAY INC"]),
    dict(slug="markel-13f", name="Markel (13F holdings)", manager="Tom Gayner", style="conc", search=["MARKEL CORP", "MARKEL GROUP INC"]),
    dict(slug="fairfax-13f", name="Fairfax Financial (13F holdings)", manager="Prem Watsa", style="conc", search=["FAIRFAX FINANCIAL HOLDINGS"]),
    dict(slug="gardner-russo", name="Gardner Russo & Quinn", manager="Tom Russo", style="conc", search=["GARDNER RUSSO & QUINN", "GARDNER RUSSO & GARDNER"]),
    dict(slug="semper-augustus", name="Semper Augustus", manager="Chris Bloomstran", style="conc", search=["SEMPER AUGUSTUS INVESTMENTS GROUP"]),
    dict(slug="giverny", name="Giverny Capital", manager="François Rochon", style="conc", search=["GIVERNY CAPITAL"]),
    dict(slug="greenhaven-road", name="Greenhaven Road", manager="Scott Miller", style="conc", search=["GREENHAVEN ROAD"]),
    dict(slug="punch-card", name="Punch Card Management", manager="Norbert Lou", style="conc", search=["PUNCH CARD MANAGEMENT"]),
    dict(slug="hitchwood", name="Hitchwood Capital", manager="James Crichton", style="ls", search=["HITCHWOOD CAPITAL MANAGEMENT"]),
    dict(slug="tudor", name="Tudor Investment Corp", manager="Paul Tudor Jones", style="macro", search=["TUDOR INVESTMENT CORP"]),
    dict(slug="moore", name="Moore Capital", manager="Louis Bacon", style="macro", search=["MOORE CAPITAL MANAGEMENT"]),
    dict(slug="caxton", name="Caxton Associates", manager="Andrew Law", style="macro", search=["CAXTON ASSOCIATES"]),
    dict(slug="brevan-howard", name="Brevan Howard", manager="Alan Howard", style="macro", search=["BREVAN HOWARD CAPITAL MANAGEMENT"]),
    dict(slug="man-group", name="Man Group", manager="Man AHL / Numeric (quant)", style="multi", search=["MAN GROUP PLC"]),
    dict(slug="winton", name="Winton Group", manager="David Harding (quant)", style="multi", search=["WINTON GROUP"]),
    dict(slug="arrowstreet", name="Arrowstreet Capital", manager="quant", style="multi", search=["ARROWSTREET CAPITAL"]),
    dict(slug="jane-street", name="Jane Street", manager="market maker", style="mm", search=["JANE STREET GROUP"]),
    dict(slug="belvedere", name="Belvedere Trading", manager="market maker (options)", style="mm", search=["BELVEDERE TRADING LLC"]),
    dict(slug="fisher", name="Fisher Investments", manager="Ken Fisher", style="lo", search=["FISHER ASSET MANAGEMENT"]),
    dict(slug="kingdon", name="Kingdon Capital", manager="Mark Kingdon", style="ls", search=["KINGDON CAPITAL MANAGEMENT"]),
    dict(slug="omega", name="Omega Advisors (closed 2018)", manager="Leon Cooperman", style="ls", search=["OMEGA ADVISORS"]),
    dict(slug="passport", name="Passport Capital (closed 2019)", manager="John Burbank", style="ls", search=["PASSPORT CAPITAL"]),
    dict(slug="tourbillon", name="Tourbillon Capital (closed 2018)", manager="Jason Karp", style="ls", search=["TOURBILLON CAPITAL PARTNERS"]),
    dict(slug="valinor", name="Valinor Management", manager="David Gallo", style="ls", search=["VALINOR MANAGEMENT"]),
    dict(slug="glenhill", name="Glenhill Advisors", manager="Glenn Krevlin", style="ls", search=["GLENHILL ADVISORS"]),
    dict(slug="third-avenue", name="Third Avenue Management", manager="Marty Whitman legacy", style="conc", search=["THIRD AVENUE MANAGEMENT"]),
    dict(slug="oaktree", name="Oaktree Capital", manager="Howard Marks", style="event", search=["OAKTREE CAPITAL MANAGEMENT"]),
    dict(slug="canyon", name="Canyon Capital", manager="Josh Friedman", style="event", search=["CANYON CAPITAL ADVISORS"]),
    dict(slug="anchorage", name="Anchorage Capital", manager="Kevin Ulrich", style="event", search=["ANCHORAGE CAPITAL GROUP"]),
    dict(slug="york", name="York Capital", manager="Jamie Dinan", style="event", search=["YORK CAPITAL MANAGEMENT"]),
    dict(slug="highfields", name="Highfields Capital (closed 2018)", manager="Jonathon Jacobson", style="ls", search=["HIGHFIELDS CAPITAL MANAGEMENT"]),
    dict(slug="perry", name="Perry Capital (closed 2016)", manager="Richard Perry", style="event", search=["PERRY CORP"]),
]
